### ISSUE TITLE
EventFiringWebDriver is still being used, but it has been deprecated

### ISSUE THREAD

**Issue by twalshcsv** [CognizantOpenSource/maqs-java#49]
**Describe the bug**
Using a deprecated [EventFiringWebDriver](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/events/EventFiringWebDriver.html)
See: https://github.com/CognizantOpenSource/maqs-java/blob/bf794ff52d31698fdea6cbdcec8ccb91d8c95254/jmaqs-selenium/src/main/java/com/magenic/jmaqs/selenium/SeleniumDriverManager.java#L73

**Additional context**
Should transition to [EventFiringDecorator](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/events/EventFiringDecorator.html)

**Comment by jredingcsv** [comment]
@twalshcsv I have linked the PR that contains that change. The PR will be ready soon
